version: '3.8'

services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: findmyasso_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: findmyasso
      POSTGRES_USER: findmyasso
      POSTGRES_PASSWORD: findmyasso
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - findmyasso_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U findmyasso -d findmyasso"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serveur mail pour le développement (Mailpit)
  mailpit:
    image: axllent/mailpit:latest
    container_name: findmyasso_mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"  # Interface web Mailpit
      - "1025:1025"  # Port SMTP
    networks:
      - findmyasso_network
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: "1"
      MP_SMTP_AUTH_ALLOW_INSECURE: "1"

  # Redis pour le cache et les sessions (optionnel)
  redis:
    image: redis:7-alpine
    container_name: findmyasso_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - findmyasso_network
    command: redis-server --appendonly yes

  # PHP-FPM avec extensions (optionnel, pour production)
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: findmyasso_php
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - findmyasso_network
    depends_on:
      - postgres
      - redis

  # Nginx (optionnel, pour production)
  nginx:
    image: nginx:alpine
    container_name: findmyasso_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
    networks:
      - findmyasso_network
    depends_on:
      - php

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  findmyasso_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
